finished sell stocks use case
awesominat/stonks pull request #31
Opened 2023-11-09 23:30 UTC by gursi26

finished full sell stocks use case with interactor, boundary, input/output data, presenter, state and viewmodel

2023-11-09 23:47 UTC, awesominat commented on src/interface_adapters/Sell/SellViewModel.java
> +    // TODO: Ricky
we can remove this

2023-11-09 23:51 UTC, awesominat requested changes

2023-11-09 23:51 UTC, awesominat commented on src/interface_adapters/Sell/SellPresenter.java
> +        portfolioViewModel.firePropertyChanged();
portfolioViewModel is always null, you forgot to add it in the constructor

2023-11-12 23:27 UTC, gursi26 commented
Changes made in 17e33d0

2023-11-13 00:25 UTC, awesominat approved these changes

2023-11-13 00:25 UTC, merged