GetInfo use case implemented
awesominat/stonks pull request #45
Opened 2023-11-17 21:00 UTC by quiz3

I implemented the GetInfo use_case but I also modified a bunch of files cuz the switch to Maven format messed with all the imports so I needed to change a whole bunch of stuff.

Very important to thoroughly review this one though.

2023-11-18 00:01 UTC, awesominat approved these changes
I really like this, the public methods are documented, no CA engine violations, and a good choice of what to show the user for the GetInfo case.

I think this might go in the Buy Menu after a user searches for a specific stock so they can make sure this is the stock they wanted to buy

2023-11-19 02:57 UTC, awesominat commented
I will merge this as soon as we have the new JSON data loader merged

2023-11-19 04:19 UTC, awesominat requested changes
I think the documentation can be improved. this should help clear up any confusion about the doc in the future. very good start though

2023-11-19 04:19 UTC, awesominat commented on src/main/java/use_cases/GetInfo/GetInfoInteractor.java
> +         */
I feel that the documentation needs to mention what the use case does, or rather, what the execute method does. currently, it just says it does the bulk of the use case, what does that mean?

Also, I don't think you need to mention it follows CA engine rules, the client doesn't really care about that. Instead, mention that the InputData contains the ticker

2023-11-20 20:47 UTC, quiz3 commented
I have been informed that it is not bad that this is failing. It is likely due to the fact that this branch was created prior to some of the newer Maven architecture of our project being set up. 

The merge process for this will be non-trivial but not very difficult, since all I modified most recently was the interaction.

2023-11-20 22:55 UTC, awesominat approved these changes
lgtm, thanks for the documentation changes

2023-11-20 22:55 UTC, merged